import { jsx as _jsx, Fragment as _Fragment, jsxs as _jsxs } from "react/jsx-runtime";
import { ArrowLeft, ArrowRight, ArrowDown, RotateCw, Play, Pause, RefreshCw } from 'lucide-react';
const MobileControls = ({ onMoveLeft, onMoveRight, onMoveDown, onRotate, onDrop, onPause, onRestart, isPaused, isGameOver }) => {
    return (_jsxs("div", { className: "lg:hidden flex flex-col gap-3 w-full max-w-sm mt-3", children: [_jsxs("div", { className: "flex gap-2", children: [_jsx("button", { onClick: onPause, disabled: isGameOver, className: `flex-1 flex items-center justify-center gap-2 py-3 px-4 rounded-xl font-bold transition-all
              ${isGameOver ? 'opacity-50 cursor-not-allowed bg-slate-700 text-slate-400'
                            : isPaused ? 'bg-amber-500 hover:bg-amber-400 text-slate-900 shadow-[0_0_15px_rgba(245,158,11,0.5)]'
                                : 'bg-slate-700 hover:bg-slate-600 text-white'}`, children: isPaused ? _jsxs(_Fragment, { children: [_jsx(Play, { size: 18 }), " RESUME"] }) : _jsxs(_Fragment, { children: [_jsx(Pause, { size: 18 }), " PAUSE"] }) }), _jsxs("button", { onClick: onRestart, className: "flex-1 flex items-center justify-center gap-2 py-3 px-4 bg-red-500/20 hover:bg-red-500 hover:text-white text-red-500 border border-red-500/50 rounded-xl font-bold transition-all", children: [_jsx(RefreshCw, { size: 18 }), " RESTART"] })] }), _jsxs("div", { className: "flex justify-between items-end gap-4 h-32 px-4", children: [_jsxs("div", { className: "grid grid-cols-3 gap-2 w-[180px]", children: [_jsx("div", { className: "col-start-1 row-start-2", children: _jsx("button", { className: "w-full aspect-square bg-slate-700 active:bg-slate-600 rounded-full flex items-center justify-center text-white shadow-lg active:scale-95 transition-transform", onClick: (e) => { e.preventDefault(); onMoveLeft(); }, children: _jsx(ArrowLeft, { size: 24 }) }) }), _jsx("div", { className: "col-start-2 row-start-2", children: _jsx("button", { className: "w-full aspect-square bg-slate-700 active:bg-slate-600 rounded-full flex items-center justify-center text-white shadow-lg active:scale-95 transition-transform", onClick: (e) => { e.preventDefault(); onMoveDown(); }, children: _jsx(ArrowDown, { size: 24 }) }) }), _jsx("div", { className: "col-start-3 row-start-2", children: _jsx("button", { className: "w-full aspect-square bg-slate-700 active:bg-slate-600 rounded-full flex items-center justify-center text-white shadow-lg active:scale-95 transition-transform", onClick: (e) => { e.preventDefault(); onMoveRight(); }, children: _jsx(ArrowRight, { size: 24 }) }) })] }), _jsxs("div", { className: "flex flex-col gap-4", children: [_jsx("button", { className: "w-16 h-16 bg-blue-600 active:bg-blue-500 rounded-full flex items-center justify-center text-white shadow-[0_4px_0_theme(colors.blue.800)] active:shadow-none active:translate-y-1 transition-all", onClick: (e) => { e.preventDefault(); onRotate(); }, children: _jsx(RotateCw, { size: 28 }) }), _jsx("button", { className: "w-20 h-20 bg-emerald-500 active:bg-emerald-400 rounded-full flex items-center justify-center text-white shadow-[0_6px_0_theme(colors.emerald.700)] active:shadow-none active:translate-y-1 transition-all -ml-6", onClick: (e) => { e.preventDefault(); onDrop(); }, children: _jsx("span", { className: "font-bold text-lg tracking-widest", children: "DROP" }) })] })] })] }));
};
export default MobileControls;
