import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { getCategoryName, getCategoryColor, getTimeAgo } from '@faithportal/core-utils';
export const Button = ({ children, onClick, className = "" }) => (_jsx("button", { onClick: onClick, className: `px-4 py-2 font-bold rounded-lg transition-all duration-200 ${className}`, children: children }));
export const Card = ({ children, className = "" }) => (_jsx("div", { className: `content-card p-6 ${className}`, children: children }));
export const NewsCard = ({ news, index, isBookmarked = false, onBookmarkToggle, hideActions = false, onVote }) => {
    const timeAgo = getTimeAgo(news.published_at || news.created_at);
    const categoryColor = getCategoryColor(news.category);
    const isAnalyzed = (news.title.includes('환율') || news.title.includes('주가') || news.title.includes('증시') || news.title.includes('달러') || news.title.includes('코스피') || news.title.includes('경제'));
    let keywords = [];
    if (news.relatedStocks && news.relatedStocks.length > 0) {
        keywords = news.relatedStocks.map((s) => s.name);
    }
    else if (news.tags) {
        keywords = typeof news.tags === 'string' ? news.tags.split(',').map((t) => t.trim()).filter(Boolean) : news.tags;
    }
    return (_jsxs("a", { href: `/news/${news.news_id || news.id}`, "data-index": index, className: "news-card block border-b border-gray-100 last:border-0 p-5 hover:bg-gray-50 transition-colors group relative cursor-pointer group", children: [_jsxs("div", { className: "flex-1 min-w-0", children: [_jsxs("div", { className: "flex items-center gap-2 mb-2", children: [_jsx("span", { className: `badge ${categoryColor}`, children: getCategoryName(news.category) }), _jsx("span", { className: "text-gray-500 text-[11px] font-bold flex-shrink-0", children: timeAgo }), isAnalyzed && (_jsxs("span", { className: "ml-1 px-1.5 py-0.5 rounded text-[10px] font-bold bg-purple-100 text-purple-700 border border-purple-200", children: [_jsx("i", { className: "fas fa-chart-line mr-1" }), "\uBD84\uC11D\uB428"] }))] }), _jsx("p", { className: "text-gray-900 group-hover:text-brand-green-hover font-semibold text-sm leading-snug line-clamp-2", children: news.title })] }), (keywords.length > 0 || !hideActions) && (_jsxs("div", { className: "flex items-center justify-between mt-3 pt-2 border-t border-transparent group-hover:border-gray-100 transition-colors", children: [_jsx("div", { className: "flex flex-wrap items-center gap-1.5 flex-1 pr-4", children: keywords.slice(0, 3).map((kw, i) => (_jsxs("span", { className: "px-2 py-0.5 bg-gray-50 text-gray-500 hover:bg-gray-100 transition-colors rounded text-[10px] font-medium whitespace-nowrap border border-gray-200", children: ["#", kw] }, i))) }), !hideActions && (_jsxs("div", { className: "flex items-center justify-end gap-3 flex-shrink-0", children: [_jsxs("div", { className: "flex items-center gap-3 mr-2 border-r border-gray-200 pr-3", children: [_jsxs("button", { onClick: (e) => { e.preventDefault(); if (onVote)
                                            onVote(news.news_id || news.id, 'up'); }, className: `transition-transform hover:scale-110 flex items-center gap-1 ${(news.vote_up || 0) > 0 ? 'text-red-500 font-bold' : 'text-gray-400 hover:text-red-500'}`, title: "\uC88B\uC544\uC694", children: [_jsx("i", { className: `${(news.vote_up || 0) > 0 ? 'fas' : 'far'} fa-thumbs-up` }), news.vote_up > 0 && _jsx("span", { className: "text-[10px]", children: news.vote_up })] }), _jsxs("button", { onClick: (e) => { e.preventDefault(); if (onVote)
                                            onVote(news.news_id || news.id, 'down'); }, className: `transition-transform hover:scale-110 flex items-center gap-1 ${(news.vote_down || 0) > 0 ? 'text-blue-500 font-bold' : 'text-gray-400 hover:text-blue-500'}`, title: "\uC2EB\uC5B4\uC694", children: [_jsx("i", { className: `${(news.vote_down || 0) > 0 ? 'fas' : 'far'} fa-thumbs-down` }), news.vote_down > 0 && _jsx("span", { className: "text-[10px]", children: news.vote_down })] })] }), _jsx("button", { onClick: (e) => { e.preventDefault(); if (onBookmarkToggle)
                                    onBookmarkToggle(news.news_id || news.id); }, className: `text-gray-400 hover:text-yellow-500 transition-transform hover:scale-110 ${isBookmarked ? 'text-yellow-500' : ''}`, title: "\uBD81\uB9C8\uD06C", children: _jsx("i", { className: `${isBookmarked ? 'fas' : 'far'} fa-bookmark` }) }), _jsx("button", { onClick: (e) => {
                                    e.preventDefault();
                                    if (navigator.share) {
                                        navigator.share({ title: news.title, url: `/news/${news.news_id || news.id}` });
                                    }
                                }, className: "text-gray-400 hover:text-blue-500 transition-transform hover:scale-110", title: "\uACF5\uC720", children: _jsx("i", { className: "fas fa-share-alt" }) })] }))] }))] }));
};
export const Header = ({ user, onLogout } = {}) => (_jsx(_Fragment, { children: _jsx("header", { className: "header-gradient text-white py-1", children: _jsxs("div", { className: "max-w-6xl mx-auto px-4 flex justify-between items-center h-10", children: [_jsxs("div", { className: "flex items-center gap-4", children: [_jsx("a", { href: "/", className: "font-black text-xl tracking-tighter hover:opacity-90 transition-opacity", children: "FaithPortal" }), _jsxs("nav", { className: "hidden sm:flex gap-4 text-xs font-bold", children: [_jsx("a", { href: "/news", className: "hover:text-green-100 uppercase", children: "News" }), _jsx("a", { href: "/lifestyle", className: "hover:text-green-100 uppercase", children: "Utility" }), _jsx("a", { href: "/finance", className: "hover:text-green-100 uppercase", children: "Finance" }), _jsx("a", { href: "/game", className: "hover:text-green-100 uppercase", children: "Games" })] })] }), _jsx("div", { className: "flex items-center gap-3", children: user ? (_jsxs(_Fragment, { children: [_jsxs("span", { className: "text-xs font-bold", children: [user.name, "\uB2D8"] }), _jsx("div", { className: "w-[1px] h-3 bg-white/30" }), _jsx("a", { href: "/mypage", className: "text-xs font-bold hover:text-green-100 transition-colors", children: "\uB9C8\uC774\uD398\uC774\uC9C0" }), _jsx("div", { className: "w-[1px] h-3 bg-white/30" }), _jsx("button", { onClick: onLogout, className: "text-xs font-bold hover:text-green-100 transition-colors", children: "\uB85C\uADF8\uC544\uC6C3" })] })) : (_jsxs(_Fragment, { children: [_jsx("a", { href: "/login", className: "text-xs font-bold hover:text-green-100 transition-colors", children: "\uB85C\uADF8\uC778" }), _jsx("div", { className: "w-[1px] h-3 bg-white/30" }), _jsx("a", { href: "/signup", className: "text-xs font-bold hover:text-green-100 transition-colors", children: "\uD68C\uC6D0\uAC00\uC785" })] })) })] }) }) }));
export const QuickMenu = () => (_jsx("nav", { className: "mb-16 max-w-4xl mx-auto", id: "quick-menu", children: _jsx("div", { className: "overflow-x-auto hide-scrollbar -mx-4 px-4 sm:mx-0 sm:px-0 py-4", children: _jsx("div", { className: "flex justify-start sm:justify-center items-center gap-4 sm:gap-6 lg:gap-8 min-w-max", children: [
                { label: '뉴스', icon: 'fa-newspaper', bg: 'bg-blue-50', color: 'text-blue-600', href: '/news' },
                { label: '유틸리티', icon: 'fa-home', bg: 'bg-green-50', color: 'text-green-600', href: '/lifestyle' },
                { label: '게임', icon: 'fa-gamepad', bg: 'bg-purple-50', color: 'text-purple-600', href: '/game' },
                { label: '금융', icon: 'fa-won-sign', bg: 'bg-orange-50', color: 'text-orange-600', href: '/finance' },
                { label: '쇼핑', icon: 'fa-shopping-bag', bg: 'bg-pink-50', color: 'text-pink-600', href: '/shopping' },
                { label: '엔터', icon: 'fa-film', bg: 'bg-red-50', color: 'text-red-600', href: '/entertainment' },
                { label: '교육', icon: 'fa-graduation-cap', bg: 'bg-indigo-50', color: 'text-indigo-600', href: '/education' },
            ].map((item) => (_jsxs("a", { href: item.href, className: "group text-center flex-shrink-0", children: [_jsx("div", { className: `w-14 h-14 sm:w-16 sm:h-16 mx-auto mb-2 rounded-2xl ${item.bg} shadow-sm flex items-center justify-center transition-all duration-300 group-hover:-translate-y-2 group-hover:shadow-[0_8px_16px_rgba(0,0,0,0.1)] group-hover:ring-2 group-hover:ring-brand-green`, children: _jsx("i", { className: `fas ${item.icon} text-xl sm:text-2xl ${item.color} group-hover:scale-110 transition-transform` }) }), _jsx("p", { className: "text-[11px] sm:text-xs text-gray-800 font-bold group-hover:text-brand-green transition-colors", children: item.label })] }, item.label))) }) }) }));
export const Footer = () => (_jsx("footer", { className: "bg-white border-t border-gray-200 mt-20 py-12", children: _jsxs("div", { className: "max-w-6xl mx-auto px-4", children: [_jsxs("div", { className: "flex flex-col md:flex-row justify-between gap-8 mb-8", children: [_jsxs("div", { children: [_jsx("h2", { className: "text-xl font-black text-gray-900 mb-4", children: "FaithPortal" }), _jsx("p", { className: "text-sm text-gray-500 max-w-xs leading-relaxed", children: "\uC138\uC0C1\uC758 \uBAA8\uB4E0 \uC815\uBCF4\uB97C \uD558\uB098\uB85C \uBB36\uB294 \uBBFF\uC74C\uC758 \uD3EC\uD138. \uB354 \uB098\uC740 \uB0B4\uC77C\uC744 \uC704\uD574 \uB9E4\uC77C \uC131\uC7A5\uD569\uB2C8\uB2E4." })] }), _jsx("div", { className: "grid grid-cols-2 sm:grid-cols-3 gap-8", children: _jsxs("div", { children: [_jsx("h4", { className: "font-bold text-gray-900 mb-4 text-sm", children: "\uC11C\uBE44\uC2A4" }), _jsxs("ul", { className: "space-y-2 text-sm text-gray-500", children: [_jsx("li", { children: _jsx("a", { href: "/news", className: "hover:text-brand-green transition-colors", children: "\uB274\uC2A4" }) }), _jsx("li", { children: _jsx("a", { href: "/lifestyle", className: "hover:text-brand-green transition-colors", children: "\uC720\uD2F8\uB9AC\uD2F0" }) }), _jsx("li", { children: _jsx("a", { href: "/finance", className: "hover:text-brand-green transition-colors", children: "\uAE08\uC735" }) })] })] }) })] }), _jsxs("div", { className: "pt-8 border-t border-gray-100 flex flex-col sm:row items-center justify-between gap-4", children: [_jsx("p", { className: "text-xs text-gray-400", children: "\u00A9 2026 FaithPortal. All rights reserved." }), _jsxs("div", { className: "flex gap-4 text-gray-400 text-sm", children: [_jsx("a", { href: "#", className: "hover:text-gray-600", children: _jsx("i", { className: "fab fa-facebook" }) }), _jsx("a", { href: "#", className: "hover:text-gray-600", children: _jsx("i", { className: "fab fa-twitter" }) }), _jsx("a", { href: "#", className: "hover:text-gray-600", children: _jsx("i", { className: "fab fa-instagram" }) })] })] })] }) }));
