import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Trophy, HelpCircle, ArrowRight, ArrowLeft, ArrowDown, RotateCw, Pause, Play, RefreshCw } from 'lucide-react';
import NextPiecePreview from './NextPiecePreview';
const InfoPanel = ({ score, level, lines, nextPieceType, isPaused, isGameOver, onPause, onRestart }) => {
    return (_jsxs("div", { className: "flex flex-col gap-6 w-full max-w-[200px] text-white", children: [_jsxs("div", { className: "bg-slate-800 rounded-xl p-4 border-2 border-slate-700 shadow-xl relative overflow-hidden group", children: [_jsx("div", { className: "absolute inset-0 bg-gradient-to-br from-emerald-500/10 to-transparent" }), _jsxs("div", { className: "relative z-10 flex flex-col gap-1 items-center", children: [_jsxs("span", { className: "text-emerald-400 font-bold tracking-wider text-sm flex items-center gap-2", children: [_jsx(Trophy, { size: 16 }), " SCORE"] }), _jsx("span", { className: "text-3xl font-mono font-bold text-white tabular-nums drop-shadow-md", children: score.toLocaleString() })] })] }), _jsxs("div", { className: "flex gap-4", children: [_jsxs("div", { className: "flex-1 bg-slate-800 rounded-xl p-3 border-2 border-slate-700 shadow-lg flex flex-col items-center", children: [_jsx("span", { className: "text-slate-400 font-semibold text-xs mb-1 tracking-widest", children: "LEVEL" }), _jsx("span", { className: "text-xl font-mono font-bold text-yellow-400", children: level })] }), _jsxs("div", { className: "flex-1 bg-slate-800 rounded-xl p-3 border-2 border-slate-700 shadow-lg flex flex-col items-center", children: [_jsx("span", { className: "text-slate-400 font-semibold text-xs mb-1 tracking-widest", children: "LINES" }), _jsx("span", { className: "text-xl font-mono font-bold text-cyan-400", children: lines })] })] }), _jsxs("div", { className: "bg-slate-800 rounded-xl p-4 border-2 border-slate-700 shadow-xl flex flex-col items-center", children: [_jsx("span", { className: "text-slate-400 font-bold tracking-wider text-sm mb-4", children: "NEXT BLOCK" }), _jsx("div", { className: "w-24 h-24 flex items-center justify-center bg-slate-900 rounded-lg p-2 inner-shadow", children: _jsx(NextPiecePreview, { type: nextPieceType, blockSize: "w-5 h-5", borderWidth: "border-[3px]" }) })] }), _jsxs("div", { className: "hidden lg:flex flex-col gap-3", children: [_jsx("button", { onClick: onPause, disabled: isGameOver, className: `flex items-center justify-center gap-2 py-3 px-4 rounded-xl font-bold transition-all
            ${isGameOver ? 'opacity-50 cursor-not-allowed bg-slate-700 text-slate-400'
                            : isPaused ? 'bg-amber-500 hover:bg-amber-400 text-slate-900 shadow-[0_0_15px_rgba(245,158,11,0.5)]'
                                : 'bg-slate-700 hover:bg-slate-600 text-white'}`, children: isPaused ? _jsxs(_Fragment, { children: [_jsx(Play, { size: 18 }), " RESUME"] }) : _jsxs(_Fragment, { children: [_jsx(Pause, { size: 18 }), " PAUSE"] }) }), _jsxs("button", { onClick: onRestart, className: "flex items-center justify-center gap-2 py-3 px-4 bg-red-500/20 hover:bg-red-500 hover:text-white text-red-500 border border-red-500/50 rounded-xl font-bold transition-all", children: [_jsx(RefreshCw, { size: 18 }), " RESTART"] })] }), _jsxs("div", { className: "hidden lg:block mt-auto text-xs text-slate-400 bg-slate-800 p-4 rounded-xl border border-slate-700", children: [_jsxs("h4", { className: "font-bold flex items-center gap-2 mb-3 text-slate-300", children: [_jsx(HelpCircle, { size: 14 }), " CONTROLS"] }), _jsxs("div", { className: "grid grid-cols-[1fr_auto] gap-y-2", children: [_jsxs("span", { children: [_jsx(ArrowLeft, { size: 12, className: "inline mr-1" }), _jsx(ArrowRight, { size: 12, className: "inline mr-1" }), " Move"] }), _jsx("span", { className: "font-mono text-slate-500 bg-slate-900 px-1.5 py-0.5 rounded border border-slate-700", children: "\u2190 \u2192" }), _jsxs("span", { children: [_jsx(RotateCw, { size: 12, className: "inline mr-1" }), " Rotate"] }), _jsx("span", { className: "font-mono text-slate-500 bg-slate-900 px-1.5 py-0.5 rounded border border-slate-700", children: "\u2191" }), _jsxs("span", { children: [_jsx(ArrowDown, { size: 12, className: "inline mr-1" }), " Soft Drop"] }), _jsx("span", { className: "font-mono text-slate-500 bg-slate-900 px-1.5 py-0.5 rounded border border-slate-700", children: "\u2193" }), _jsx("span", { children: "\u23EC Hard Drop" }), _jsx("span", { className: "font-mono text-slate-500 bg-slate-900 px-1.5 py-0.5 rounded border border-slate-700", children: "Space" })] })] })] }));
};
export default InfoPanel;
